### ISSUE TITLE
client/server

### ISSUE THREAD

**Issue by ghost** [akio-tanaka/lickey#1]
Make this project like a Pro 🍰 

- obfs4 (https://hamy.io/post/000d/how-to-hide-obfuscate-any-traffic-using-obfs4/)
- client (rewritten to dll and use https://github.com/stephenfewer/ReflectiveDLLInjection)

**Comment by akio-tanaka** [comment]
sure. i am going to update.

**Comment by ghost** [comment]
You're planned write client/server? 

If yes - check this project https://github.com/ReactiioN1337/license-system for good ideas.

**Comment by akio-tanaka** [comment]
yes. i am going to develop floating licensing function as client / server.
thank you for your support. i will check it.

**Comment by ghost** [comment]
@akio-tanaka Regarding working with the network, do not use `libcurl`. If he the cracker decides to replace the server (`emulate server`), then he will do it very simply.
