### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by ghost** [akio-tanaka/lickey#13]
Hi!

Are you working on a project? 
If you work, what is ready? I have time to help develop

**Comment by akio-tanaka** [comment]
hi, @lurumdare 

because of trouble in my business, 
it is difficult to have time enough for your expectation actually by the end of this year.

it sounds good your support.
what kind of way is it convenient for you?

**Comment by ghost** [comment]
1. add client/server
2. refactoring 
3. modernize code

**Comment by ghost** [comment]
git PR

**Comment by akio-tanaka** [comment]
thank you.
i will confirm the pull request tonight in Japan.

i am not familiar very much to collaborators setting of github. if you have anything you want, please don't hesitate to ask me.

**Comment by ghost** [comment]
Okay
It is easy to understand.

**Comment by LazyHippogriff** [comment]
Can this be used or is there still some work left? Some examples about how to use will surely help.

**Comment by ghost** [comment]
@vishal14101993 it is work correctly.

**Comment by LazyHippogriff** [comment]
@lurumdare I've just started to go through the code to figure out how to use this in my project. Any tips/suggestions regarding how to use this?

**Comment by ghost** [comment]
@vishal14101993 see code and use. Basic usage in `lickey_test`
