### ISSUE TITLE
virtualization issues

### ISSUE THREAD

**Issue by ghost** [akio-tanaka/lickey#2]
If you use virtualization (`VMProtect/Themida/Enigma/SafeEngine`) need bypass vulnerable external calls.

Example: leak password from `strcmp` if function not protect.

Using `__forceinline` solve this problem.

Maybe create branch?

**Comment by akio-tanaka** [comment]
after updating document, i will start to handle it. but because that is  not my expertise, to fix it may take time.

if you want to make branch and fix, it sounds great.
