### ISSUE TITLE
Formatting with AStyle

### ISSUE THREAD

**Issue by ghost** [akio-tanaka/lickey#6]
My propose about this extension
https://marketplace.visualstudio.com/items?itemName=Lukamicoder.AStyleExtension2017
https://github.com/lukamicoder/astyle-extension (VS 2019)

Make please config, and share.

**Comment by ghost** [comment]
@akio-tanaka or .clang-format

**Comment by akio-tanaka** [comment]
i will use the formatter.

**Comment by ghost** [comment]
Okay. Add please config file to project.

**Comment by akio-tanaka** [comment]
i have already added AStyle Formatter setting into "tools" folder in master branch
