### ISSUE TITLE
C Run-Time Libraries (CRT)

### ISSUE THREAD

**Issue by ghost** [akio-tanaka/lickey#7]
I think that the use of CRT will be a weak point in this project. What do you think?

**Comment by ghost** [comment]
Linked projects:
https://github.com/liupengs/Mini-CRT
https://github.com/wbenny/mini-tor/blob/master/mini/crt/crt0.h

**Comment by ghost** [comment]
This project good demo 
https://github.com/skyformat99/miniexe

**Comment by akio-tanaka** [comment]
thank you. it must be implemented for cracking with replacing standard libraries. i will check the project.

**Comment by ghost** [comment]
Priority for this is low.

If you are a good programmer, then knowing the device will be useful when writing a strong library without CRT in pure C.

Good ownership of the debugger is also important.
